### ISSUE TITLE
vee is gae

### ISSUE THREAD

**Issue by aquaticdosDev** [Vee-Gae/vee#1]
how do we fix it

**Comment by Vee-Gae** [comment]
i do not know

**Comment by Vee-Gae** [comment]
can you try to add some code that will fix the problem? oh wait, you can't fix that. 
it's vee

**Comment by aquaticdosDev** [comment]
it would have been weird if it was fixable

**Comment by Vee-Gae** [comment]
yeah, i am going to add the main source soon

**Comment by Vee-Gae** [comment]
> 
> 
> yeah, i am going to add the main source soon

@aquaticdosDev did that! #2
